name: credit-bank
channels:
  - default
  - conda-forge
  - anaconda
dependencies:
  - jupyter=1.0.0
  - numpy=1.18.5
  - pandas=1.0.5
  - python=3.7.7
  - scikit-learn=0.23.1
  - pip=20.1.1
  - seaborn=0.10.1
  - plotly=4.9.0
  - matplotlib=3.2.2
